[package]
name = "egui-rad-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
egui = { version = "0.33", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
